### ISSUE TITLE
ROADMAP 2024

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/ragflow#1821]
# v0.15.0
- [x] #3794
- [x] #3759
- [x] Supports [Kubernetes](https://kubernetes.io/) deployment #864
- [x] #3851
- [x] #3909
- [x] #3993
- [x] #4045 ##3793
- [x] #4052

# v0.14.0
- [x] Supports Infinity as the alternative database to elasticsearch. #2894
- [x] #3556
- [x] #3560
- [x] #3243 #3105
- [x] Refine the variable definition for agent. #3240 #3355
- [x] #3361
- [x] Improve search performance. #3380
- [x] Enhance the monitoring and visualization of task execution. #3409 #3401

# v0.13.0

- [x] Better chunking algorithms for long text document. #2687
- [x] Add more tools to agent. #1739 #2908 #3085
- [x] #2970
- [x] Supports single team per user. #2834
- [x] #2846
- [x] Python and HTTP API #1102

# v0.12.0
- [x] Adds an investment consultant agent template. #1739
- [x] Adds a gerneral purpose agent template. #2478
- [x] Supports huggingface deployed models. #2469
- [x] Multi-turn conversation optimization. #2362 #2484
- [x] Supports model provider deletion. #2376
- [x] Reduces the docker image size. #2295

# v0.11.0
- [x] Supports search mode chat. #2247
- [x] Support TTS to generated text. ##1877
- [x] Add more tools to agent. #1739
- [x] Add Medical consultation agent template. #1739
- [x] Support PostgresSQL Database #2356

# v0.10.0
- [x] Supports Agent API #1842 #1788
- [x] Supports chatting with files/images #1880
- [x] Support Text2SQL through RAG #1965
- [x] Move files in file manager #1826
- [x] Add more tools to agent #1739
- [x] Supports more interfaces to LLM. #1853
- [x] Supports monitor of task executor. #1383

# v0.9.0
- [x] Support GraphRAG, mind map generation. #1594
- [x] #1739
- [x] Support parsing audio files.  #1514 
- [x] Support XInference rerank model #1455
- [x] Support Gemini/Groq/nvidia/openRouter/LM Studio #1036 #1432 #1602

# v0.8.0
- [x] Support RAG graph orchestration and workflow #918
- [x] Support Self RAG #1069
- [x] Support several operators for initial agent/workflow

# v0.7.0

- [x] Implements [RAPTOR](https://arxiv.org/html/2401.18059v1) for better chunking. #882
- [x] Supports ARM platform. #842 
- [x] Supports HTML file.
- [x] Integrates reranker.

# v0.6.0

- [x] Print version or commit-id when RAGFlow is started. Or showing these information on UI. #643 
- [x] Chunks retrieval APIs #821 
- [x] Files in knowledge base should also be found in file manager. #800
- [x] System components monitoring. #848 
- [x] Supports simple document layout to speed up file parsing.#799
- [x] Streaming conversation output. #709
- [x] Default language will be given according to the browse setting and also can be configured. #801

---
# Long-term plan

- [ ] RAGFlow documents #720 
- [ ] APIs #1102
