### ISSUE TITLE
ROADMAP 2025

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/ragflow#4214]
## v0.16.0
- [ ] Support memory API for Agent #4213
- [ ] Support planning for Agent 
- [ ] Support light version of GraphRAG(Without community)
- [ ] Support fast version of GraphRAG
- [ ] Support Loop within Agent
- [ ] Support metadata(TAG) for document chunk and query.

## Previous roadmap

[ROADMAP 2024](https://github.com/infiniflow/ragflow/issues/1821)

**Comment by Jeocy** [comment]
Does RAGFlow not have an administrator entrance?

**Comment by alexxchen** [comment]
How about supporting multi-modal RAG?

**Comment by chminsc** [comment]
mobile ui please
option to disable user registration

**Comment by Ruler27** [comment]
user management method, currently if I expose it to the internet, anyone can register

**Comment by hoharald** [comment]
UX improvements for the chat

- multiple lines for chat input (HTML tag input => textarea)
- markdown rendering, since response from LLMs supports it

**Comment by 15053285989** [comment]
希望支持导出和导入agent工作流
Hope to support exporting and importing Agent workflows.

**Comment by yingfeng** [comment]
> How about supporting multi-modal RAG?

Under planning, it requires Infinity to be production ready such that Tensor based reranker as well as multi vector retrieval could be available.

**Comment by hanxxiang5201** [comment]
希望知识库可以分享一个连接，这样别人点看，可以询问问题，不用登录平台，类似与分享了一个聊天界面，上面可以定义机器人可以提供什么服务

**Comment by cike8899** [comment]
> 希望支持导出和导入agent工作流 Hope to support exporting and importing Agent workflows.

Already supported

![Image](https://github.com/user-attachments/assets/6d62969f-b81c-4611-8e46-2a7d098f7d8a)

**Comment by Andy-Zyu** [comment]
How do I need to be able to call the visual understanding model in the agent? Can the user call the corresponding visual understanding model after uploading the picture?

**Comment by zmxccxy** [comment]
1、新建助理，可以不选择关联知识库，就只与大模型对话。
2、助理的对话页面美化下，比如对话框颜色、小组件按钮、进行中/加载中的提示。助理的对话框显示效果支持更多格式，比如md、code等。对话输入框支持语音输入。设置了助理头像后，新建对话，还是默认的头像，需要过一段时间才行。
3、agent，可以自定义头像。
4、模型供应商，已加入的，显示面积可以调整下，太宽了。
5、完善第三方嵌入，要显示助理标题和头像。

感谢🙏

**Comment by rplescia** [comment]
> user management method, currently if I expose it to the internet, anyone can register PostgresSQL support

I agree with user management, this feature is needed very much. Even if it is basic user management to start with, the ability to disable user registration and only invite users by email.

Ideally, it would be great if we could get the following user management features

- User management page with the ability to invite/disable/remove users and add users to groups
    - Admin group (full system access with user management)
    - Standard group (can access everything except 'user management' and 'system' features) 
- Multiple teams 
    - The ability to create multiple teams and add different people to each team. I don't always want to share a knowledge base with everyone in my team, I need a way to manage my teams and the people in each team so that I can maintain some knowledge base security

**Comment by yumu7777777** [comment]
> 请支持 SSO/IAM

您好SSO/IAM 有好用的开源项目吗

**Comment by yingfeng** [comment]
SSO/IAM belong to features of enterprise edition and will not be delivered in the open source edition.

**Comment by dalemccrory** [comment]
Regarding SSO and enterprise/open source, I like what Windmill.dev does... https://www.windmill.dev/pricing Maybe you could consider that versus having a hard SSO tax.

**Comment by igorperic17** [comment]
User management is a showstopper for our company as well. Specifically, we have no way to build a knowledge base which is visible to only a certain group of users (i.e. financial data or HR data).

**Comment by wzqiang1332** [comment]
Expect to support script nodes or function nodes, and support the use of script functions to process the input of the previous node and then output

**Comment by Tsukasa007** [comment]
希望 Agent 支持变量执行代码块

**Comment by Luyp-m** [comment]
Hope to support statistical analysis of all users’ questions and answers, such as tracking the usage volume and frequency over a quarter, identifying the topics they focus on, and calculating the ratio of effective to ineffective responses.

**Comment by stardyun** [comment]
Hope to support agent api to dynamically change the variables of begin component

**Comment by Sos-Zachary** [comment]
> Does RAGFlow not have an administrator entrance?RAGFlow 没有管理员入口吗？

I think it would be nice if we had a back office to monitor api calls, like langsmith/langfuse

**Comment by role11** [comment]
recommend refining the API interface and addressing existing issues to improve its overall quality, as the current implementation appears somewhat rudimentary.

**Comment by yuhaya** [comment]
> > 希望支持导出和导入agent工作流
> 
> 已支持
> 
> ![Image](https://github.com/user-attachments/assets/6d62969f-b81c-4611-8e46-2a7d098f7d8a)

希望能支持API接口导入

**Comment by BuYuanHao** [comment]
I hope Aging can execute Python or JS code

**Comment by chaijl** [comment]
在文件管理中上传文件，然后连接到知识库，在知识中做了解析后发现不想要了，在知识中把该解析的知识删除，然后再回到文件管理中查看那个文件，发现文件还在，但点击最后的预览，这个文件是错误的了，一定要删除重新上传才行，这个不知道是不是bug.

**Comment by wwwwwwsaw** [comment]
你好，希望能在块预览中能展示图片信息；可以**插入**块而不是单纯新增块；在编辑块的时候，能够手动定位原始文档位置以及插入图片。

**Comment by ZhenhangTung** [comment]
> I hope Agent can execute Python or JS code

Will launch it in **v0.19.0**—stay tuned!

**Comment by ZhenhangTung** [comment]
> 你好，希望能在块预览中能展示图片信息；可以**插入**块而不是单纯新增块；在编辑块的时候，能够手动定位原始文档位置以及插入图片。

Thanks for the suggestions—these are great points!

To better understand how we can support your needs, could you share a bit more detail on each one?

**Comment by ZhenhangTung** [comment]
> 在文件管理中上传文件，然后连接到知识库，在知识中做了解析后发现不想要了，在知识中把该解析的知识删除，然后再回到文件管理中查看那个文件，发现文件还在，但点击最后的预览，这个文件是错误的了，一定要删除重新上传才行，这个不知道是不是bug.

Pls open an issue with screenshots so we can help you with this problem.

**Comment by ZhenhangTung** [comment]
> 希望Agent中增加一个output转格式的节点，可以自定义输出的格式是txt还是markdown或HTML

@hero8152 Could you share a use case for this feature request?

**Comment by ZhenhangTung** [comment]
> 1）希望增加对图片内容识别，建立知识库，并可以问答； 2）希望增加对视频内容识别，建立知识库，并可以问答。回复结果的引用，指向视频中的时间段。

@czhcc Thanks for the great suggestions!

1. **Image content recognition** is already supported in the current version.
2. For **video content recognition**, could you share more details on what you'd like to achieve?  

Understanding your use case will help us better evaluate how to support video-based knowledge indexing and retrieval. Looking forward to your thoughts!

**Comment by ZhenhangTung** [comment]
> > > 希望支持导出和导入agent工作流
> > 
> > 
> > 已支持
> > ![Image](https://github.com/user-attachments/assets/6d62969f-b81c-4611-8e46-2a7d098f7d8a)
> 
> 希望能支持API接口导入

@yuhaya Why do you need an API to export the workflow?

**Comment by ZhenhangTung** [comment]
> > Does RAGFlow not have an administrator entrance?RAGFlow 没有管理员入口吗？
> 
> I think it would be nice if we had a back office to monitor api calls, like langsmith/langfuse

@Sos-Zachary Great point—we’ve already started designing a logging and monitoring module.

We’d love to hear more about what kind of insights or features you’d find most valuable.  
For example: API call history, success/failure rates, latency tracking, per-user logs, etc.?

Your input would really help shape the design—thanks!

**Comment by orkutmuratyilmaz** [comment]
AMD/ROCm support, please:)

**Comment by ZhenhangTung** [comment]
@lv514577284 pls check my comment: https://github.com/infiniflow/ragflow/issues/6155#issuecomment-2939412689

**Comment by ooodwbooo** [comment]
1. It is hoped that the agent can be added to the built-in chat of ragflow.
2. It is hoped to add a chart generation component. (Reference: https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949)
3. It is hoped to add an administrator interface for user management, open registration settings and other configurations.

```
1. 希望agent可以加入ragflow内置的聊天中
2. 希望增加一个图表生成的组件([参考](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
3. 希望增加管理员画面进行用户管理，和是否开放注册等其他设置
```

**Comment by ZhenhangTung** [comment]
> 1. It is hoped that the agent can be added to the built-in chat of ragflow.
> 2. It is hoped to add a chart generation component. (Reference: [Is the current text-to-sql capable of outputting data analysis charts? #6732 (comment)](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
> 3. It is hoped to add an administrator interface for user management, open registration settings and other configurations.
> 
> ```
> 1. 希望agent可以加入ragflow内置的聊天中
> 2. 希望增加一个图表生成的组件([参考](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
> 3. 希望增加管理员画面进行用户管理，和是否开放注册等其他设置
> ```

> It is hoped that the agent can be added to the built-in chat of ragflow.

@ooodwbooo could you explain more?

**Comment by Nouhaila-AH** [comment]
Arabic docs Suppport

**Comment by ZhenhangTung** [comment]
> Arabic docs Suppport

@Nouhaila-AH We may offer an doc reading assistant in the future to help users with different languages understand our product better in the future. Currently you could try some Chrome LLM extensions translating our docs into Arabic.

**Comment by ooodwbooo** [comment]
> > 1. It is hoped that the agent can be added to the built-in chat of ragflow.
> > 2. It is hoped to add a chart generation component. (Reference: [Is the current text-to-sql capable of outputting data analysis charts? #6732 (comment)](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
> > 3. It is hoped to add an administrator interface for user management, open registration settings and other configurations.
> > 
> > ```
> > 1. 希望agent可以加入ragflow内置的聊天中
> > 2. 希望增加一个图表生成的组件([参考](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
> > 3. 希望增加管理员画面进行用户管理，和是否开放注册等其他设置
> > ```
> 
> > It is hoped that the agent can be added to the built-in chat of ragflow.
> 
> [@ooodwbooo](https://github.com/ooodwbooo) could you explain more?

![Image](https://github.com/user-attachments/assets/4f1ade4c-a21d-4b8a-9a88-5334ec98e179)
It is hoped that the agents created on the "agent" page can be used to ‘create an assistants’ on the "chat" page, so that chat history and other information can be retained.This also ensures that all usage is concentrated on a single page.

**Comment by ZhenhangTung** [comment]
> > > 1. It is hoped that the agent can be added to the built-in chat of ragflow.
> > > 2. It is hoped to add a chart generation component. (Reference: [Is the current text-to-sql capable of outputting data analysis charts? #6732 (comment)](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
> > > 3. It is hoped to add an administrator interface for user management, open registration settings and other configurations.
> > > 
> > > ```
> > > 1. 希望agent可以加入ragflow内置的聊天中
> > > 2. 希望增加一个图表生成的组件([参考](https://github.com/infiniflow/ragflow/issues/6732#issuecomment-2943481949))
> > > 3. 希望增加管理员画面进行用户管理，和是否开放注册等其他设置
> > > ```
> > 
> > 
> > > It is hoped that the agent can be added to the built-in chat of ragflow.
> > 
> > 
> > [@ooodwbooo](https://github.com/ooodwbooo) could you explain more?
> 
> ![Image](https://github.com/user-attachments/assets/4f1ade4c-a21d-4b8a-9a88-5334ec98e179) It is hoped that the agents created on the "agent" page can be used to ‘create an assistants’ on the "chat" page, so that chat history and other information can be retained.This also ensures that all usage is concentrated on a single page.



@ooodwbooo Session management will be introduced to both Chat, Search and Agent module. We've finished our design draft and will take some time to implement.

**Comment by saicomagic** [comment]
Support drop history. If the user's question is not related to the previous question, agent can drop the history, preventing too much historical information from affecting the answers of llm

**Comment by ZhenhangTung** [comment]
> Support drop history. If the user's question is not related to the previous question, agent can drop the history, preventing too much historical information from affecting the answers of llm

You mean deleting chat history? What if we introducing a new feature: new chat?  For example, like ChatGPT's implementation. 

<img width="765" height="112" alt="Image" src="https://github.com/user-attachments/assets/d1bcf3b4-ed79-4d18-9a0e-62f2a8a9015e" />


Related feature request: https://github.com/infiniflow/ragflow/issues/8317

**Comment by WF-Guo** [comment]
It is highly recommended to add the editing function of the knowledge graph or support the use of professional graph databases.

**Comment by ZhenhangTung** [comment]
> It is highly recommended to add the editing function of the knowledge graph or support the use of professional graph databases.

@WF-Guo Could you explain more on your idea?

**Comment by WhitePlusMS** [comment]
Hi There. Are there any plans to support calls to the OLLAMA Reranker model?
有没有计划支持OLLAMA Reranker 模型的调用呢？

**Comment by ZhenhangTung** [comment]
> Hi There. Are there any plans to support calls to the OLLAMA Reranker model? 有没有计划支持OLLAMA Reranker 模型的调用呢？

@WhitePlusMS Which reranker model are you using? Any use cases that you can share with us?

**Comment by NyaDoo** [comment]
Is mineru access planned? At present, deepdoc is indeed inferior to mineru in terms of parsing and slicing effects. Especially in terms of slicing, the current slicing effect is not as good as mineru's output. At the same time, if large model intelligent slicing can be introduced, it may bring more improvements.

**Comment by ZhenhangTung** [comment]
> Is mineru access planned? At present, deepdoc is indeed inferior to mineru in terms of parsing and slicing effects. Especially in terms of slicing, the current slicing effect is not as good as mineru's output. At the same time, if large model intelligent slicing can be introduced, it may bring more improvements.

Will review it after the v0.20.0 release.

**Comment by NyaDoo** [comment]
> > Is mineru access planned? At present, deepdoc is indeed inferior to mineru in terms of parsing and slicing effects. Especially in terms of slicing, the current slicing effect is not as good as mineru's output. At the same time, if large model intelligent slicing can be introduced, it may bring more improvements.
> 
> Will review it after the v0.20.0 release.

Ok, a few problems I'm currently encountering.
One is that there will be more typos in the parsing.
The other is a part similar to a list/sequence or table of contents, which will completely lose the newline format and become a continuous entire block of text, which is extremely poorly readable.
Then, if you slice, the slicing will also be inaccurate, and you will not be able to slice according to semantics, and the same text paragraph or table of contents will be cut into multiple fragmented blocks.

**Comment by orkutmuratyilmaz** [comment]
@WhitePlusMS have you seen [this issue](https://github.com/ollama/ollama/issues/3368)?

**Comment by frankbingsap** [comment]
> > It is highly recommended to add the editing function of the knowledge graph or support the use of professional graph databases.
> 
> [@WF-Guo](https://github.com/WF-Guo) Could you explain more on your idea?

Like save knowledge graph in Neo4j  database，  And also auto generated knowlege graph is not good enough, you may need delete some entities, add edges, merge some nodes toghter, and etc. if you can edit generated graph,  the RAG quality will be improved greatly

**Comment by simon-shi87** [comment]
> 希望知识库可以分享一个连接，这样别人点看，可以询问问题，不用登录平台，类似与分享了一个聊天界面，上面可以定义机器人可以提供什么服务

你可以用其他客户端来调用api实现

**Comment by interestingyong** [comment]
有什么performance testsuite提供吗

**Comment by ZhenhangTung** [comment]
> > > It is highly recommended to add the editing function of the knowledge graph or support the use of professional graph databases.
> > 
> > 
> > [@WF-Guo](https://github.com/WF-Guo) Could you explain more on your idea?
> 
> Like save knowledge graph in Neo4j database， And also auto generated knowlege graph is not good enough, you may need delete some entities, add edges, merge some nodes toghter, and etc. if you can edit generated graph, the RAG quality will be improved greatly

@frankbingsap appreciate your input.

**Comment by ZhenhangTung** [comment]
> Is mineru access planned? At present, deepdoc is indeed inferior to mineru in terms of parsing and slicing effects. Especially in terms of slicing, the current slicing effect is not as good as mineru's output. At the same time, if large model intelligent slicing can be introduced, it may bring more improvements.

@NyaDoo The integration is still in design, and it might not be part of our open-source release.

**Comment by NyaDoo** [comment]
> > Is mineru access planned? At present, deepdoc is indeed inferior to mineru in terms of parsing and slicing effects. Especially in terms of slicing, the current slicing effect is not as good as mineru's output. At the same time, if large model intelligent slicing can be introduced, it may bring more improvements.
> 
> [@NyaDoo](https://github.com/NyaDoo) The integration is still in design, and it might not be part of our open-source release.

oh...This is really bad news. Is it possible to open the API interface of the corresponding resolution process to support the docking and adding different resolutions?

**Comment by ZhenhangTung** [comment]
> > > Is mineru access planned? At present, deepdoc is indeed inferior to mineru in terms of parsing and slicing effects. Especially in terms of slicing, the current slicing effect is not as good as mineru's output. At the same time, if large model intelligent slicing can be introduced, it may bring more improvements.
> > 
> > 
> > [@NyaDoo](https://github.com/NyaDoo) The integration is still in design, and it might not be part of our open-source release.
> 
> oh...This is really bad news. Is it possible to open the API interface of the corresponding resolution process to support the docking and adding different resolutions?

@NyaDoo Will see if there is any solution we could offer.

**Comment by Sank-WoT** [comment]
> It is highly recommended to add the editing function of the knowledge graph or support the use of professional graph databases.

This option is very necessary, as there is no transparency in the work of GrapgRag, LightRag. And also understanding the connections

**Comment by ZhenhangTung** [comment]
> > It is highly recommended to add the editing function of the knowledge graph or support the use of professional graph databases.
> 
> This option is very necessary, as there is no transparency in the work of GrapgRag, LightRag. And also understanding the connections

@Sank-WoT Appreciate your feedback. Interestingly, when I shared this feature with China Telecom last week, their AI team leader brought up the same request.

Could you share why you need to edit the graph? What problem would this help you solve?
