### ISSUE TITLE
[Feature Request]: APIs to access knowledge base

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/ragflow#717]
### Describe the feature you'd like

- [x] Lists files of a knowledge base.
- [x] Uploads files to a knowledge base.
- [ ] Delete files from a knowledge base.
- [ ] Download files from a knowledge base.
- [x] Start to parsing a file of knowledge base. #821
- [x] Get chunks of a parsed file in JSON or text format. #821
- [ ] Delete a chunk of a parsed file by chunk id.
- [ ] Add a new chunk into a parsed file.
- [x] Specify document ID for chatting. #808

### Related issues
#710 #696 #675 #671 #490 #399 #568 #417 #389

**Comment by 23233** [comment]
Add Chunks? 
Edit Chunks?

**Comment by JinHai-CN** [comment]
> Add Chunks? Edit Chunks?

Updated.

**Comment by Yannnnnnny** [comment]
Thanks for the update. Glad to hear the issue has been resolved. Closing this issue now.
