### ISSUE TITLE
[Feature Request]: Add guides, references, best practices, and other documentation that may facilitate user journey with RAGFlow

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/ragflow#720]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- [ ] RAGFlow overview covering its advantages and what differentiates it from its peer RAG apps.
- [x] **P0:** Quickstart guide covering installation, a quick set up of a knowledge base, and starting a conversation.  #743 
- [x] **P1:** User guide for establishing a knowledge base.
- [x] **P1:** User guide for setting up an AI-based conversation.
- [x] **P1:** User guide for integrating with third-party apps using conversation API.
- [x] **P1:** User guide for uploading and managing files. #788 
- [x] **P2:** Configurations for both online LLMs and local LLM deployments (Ollama and Xinference) #1066 #1112 
- [ ] **P2:** Embedding model configurations.
- [ ] **P2:** Parsing configurations covering template options and chunking size settings. 
- [ ] **P2:** Conversation configurations (assistant, prompt, and model).
- [ ] **P2:** General configurations (credential settings, environment variable settings, and system management settings).
- [ ] Best practices: choosing chunking templates.
- [ ] Best practices: choosing embedding models.
- [ ] Best practices: system tuning. 
- [ ] FAQ (general + troubleshooting)
- [x] References: Conversation API Reference
- [ ] References: File API Reference
- [ ] References: Deepdoc API Reference
- [ ] Use cases: Contracts
- [ ] Use cases: financial reports (including tables)
- [ ] Use cases: manuals
- [ ] Use cases: chatbot
